# Generated by Django 2.1.7 on 2019-02-24 02:26

from django.db import migrations, models
import partner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to=partner.models.upload_partner_icon)),
                ('url', models.URLField()),
            ],
        ),
    ]
