# Generated by Django 2.2 on 2019-05-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulating_supply', models.FloatField()),
                ('total_supply', models.FloatField()),
                ('max_supply', models.FloatField()),
                ('cmc_rank', models.FloatField()),
                ('price_usd', models.FloatField()),
                ('volume_24h_usd', models.FloatField()),
                ('percent_change_1h_usd', models.FloatField()),
                ('percent_change_24h_usd', models.FloatField()),
                ('percent_change_7d_usd', models.FloatField()),
                ('market_cap_usd', models.FloatField()),
                ('price_btc', models.FloatField()),
                ('volume_24h_btc', models.FloatField()),
                ('percent_change_1h_btc', models.FloatField()),
                ('percent_change_24h_btc', models.FloatField()),
                ('percent_change_7d_btc', models.FloatField()),
                ('market_cap_btc', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
