# Generated by Django 2.1 on 2018-12-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181227_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(related_name='related_posts', to='blog.Post'),
        ),
    ]
