# Generated by Django 2.1.7 on 2019-02-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181227_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(related_name='other_posts', to='blog.Post'),
        ),
    ]
