# Generated by Django 2.1 on 2018-09-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
