build-docker-dev:
	cd docker/dev/ && docker build -t "callisto/callisto-website-front" .

start-dev:
	cd docker/dev/ && docker-compose up -d

stop-dev:
	cd docker/dev/ && docker-compose stop

build-docker-prod:
	cd docker/prod/ && docker build -t "callisto/callisto-website-front-prod" .

start-prod:
	cd docker/prod/ && docker-compose up -d

stop-prod:
	cd docker/prod/ && docker-compose stop
