version: '3'
services:
  callisto:
    image: callisto/callisto-website-prod
    volumes:
      - ../../../:/app/
    ports:
      - "8000:8000"
    container_name: callisto-website
    restart: on-failure
    environment:
      - TERM=xterm
      - DJANGO_SECRET_KEY="${DJANGO_SECRET_KEY}"
      - DB_CALLISTO="${DB_CALLISTO}"
      - DB_USER="${DB_USER_CALLISTO}"
      - DB_PASS="${DB_PASS_CALLISTO}"
      - DB_HOST="${DB_HOST_CALLISTO}"
    networks:
      - callisto
  callisto-postgresql:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_DB="${POSTGRES_DB}"
    container_name: callisto-postgresql
    networks:
      callisto:
        aliases:
          - callisto-postgresql
    volumes:
      - /data/postgres-callisto:/var/lib/postgresql/data
networks:
   callisto:
     external: true
