# Generated by Django 2.1.7 on 2019-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinantialReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finantial_date', models.DateField()),
                ('finantial_report', models.FileField(upload_to='finantial-report')),
            ],
        ),
    ]
