# Generated by Django 2.1 on 2018-08-08 00:25

from django.db import migrations, models
import django.db.models.deletion
import wallets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WalletPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.FileField(upload_to=wallets.models.upload_platform_icon)),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallets.WalletPlatform'),
        ),
    ]
