# Generated by Django 2.1 on 2018-11-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_auto_20181124_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='keys',
            field=models.ManyToManyField(through='translations.LanguageTranslation', to='translations.TranslationKey'),
        ),
    ]
