# Generated by Django 2.1 on 2018-12-16 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_language_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationkey',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
