# Generated by Django 2.1 on 2018-08-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.FileField(upload_to='')),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
