# Generated by Django 2.1 on 2018-08-09 00:49

from django.db import migrations, models
import exchanges.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='icon',
            field=models.FileField(upload_to=exchanges.models.upload_exchabge_icon),
        ),
    ]
