# Generated by Django 2.1 on 2018-08-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_auto_20180809_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='icon',
            new_name='logo',
        ),
    ]
