# Generated by Django 2.1 on 2018-08-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_auto_20180809_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
